### ISSUE TITLE
First launch todo list

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/zero_to_jupyterhub#1]
- [x] Improve the “extending your setup” section with explanations for requesting more resources.
- [x] Improve the oauth instructions so people know how to generate authentication credentials themselves
- [x] add a short description about asking for more resources if you have more students
- [x] Build the mechanism for people to specify new packages
- [x] Build the mechanism for people to specify a github repo they want loaded in the root folder
- [x] Add instructions for connecting a docker image / github repo / etc.
- [x] Move these docs into a repository w/ a sphinx build
